# Generated by Django 5.2.15 on 2026-06-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("contribution", "Contribution"),
                    ("payout", "Payout"),
                    ("loan_disbursement", "Loan Disbursement"),
                    ("loan_repayment", "Loan Repayment"),
                    ("social_fund", "Social Fund"),
                    ("wallet_topup", "Wallet Top-up"),
                    ("wallet_withdrawal", "Wallet Withdrawal"),
                    ("savings_deposit", "Savings Deposit"),
                    ("savings_withdrawal", "Savings Withdrawal"),
                ],
                max_length=30,
            ),
        ),
    ]
