# Generated by Django 5.2.15 on 2026-06-08 13:50

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('firebase_uid', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('mri_score', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('mri_trend', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('mri_payment_punctuality', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('mri_attendance', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('mri_loan_repayment', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('mri_contribution_consistency', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('mri_community_participation', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('badge', models.CharField(blank=True, default='', max_length=50)),
                ('is_kyc_verified', models.BooleanField(default=False)),
                ('phone_verified', models.BooleanField(default=False)),
                ('email_verified', models.BooleanField(default=False)),
                ('social_fund_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('wallet_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['-date_joined'],
            },
        ),
    ]
