# Generated by Django 5.2.15 on 2026-06-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_savings_balance_linkedaccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="celo_address",
            field=models.CharField(blank=True, default="", max_length=42),
        ),
    ]
