# Generated by Django 5.2.15 on 2026-06-12 11:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_celo_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="MriEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("delta", models.DecimalField(decimal_places=1, max_digits=4)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("late_njangi", "Late Njangi"),
                            ("missed_contribution", "Missed Contribution"),
                            ("loan_default", "Loan Default"),
                            ("membership_rejected", "Membership Rejected"),
                        ],
                        max_length=40,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "reference_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mri_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
