from django.urls import path

from groups.views import (
    AssignPickingOrderView,
    CloseSavingsPeriodView,
    ContributeSocialFundView,
    DueDatesView,
    GroupDetailView,
    GroupListCreateView,
    GroupMessageListCreateView,
    GroupPreviewView,
    GroupReconciliationView,
    GroupSavingsView,
    GroupSearchView,
    JoinGroupView,
    MembershipRequestListView,
    PlayNjangiView,
    RespondMembershipRequestView,
    SavingsDepositView,
    SavingsWithdrawView,
    SocialFundListCreateView,
    StartSavingsPeriodView,
)

urlpatterns = [
    path('groups/', GroupListCreateView.as_view(), name='group-list'),
    path('groups/search/', GroupSearchView.as_view(), name='group-search'),
    path('groups/due-dates/', DueDatesView.as_view(), name='group-due-dates'),
    path('groups/join/', JoinGroupView.as_view(), name='group-join'),
    path('groups/<uuid:pk>/', GroupDetailView.as_view(), name='group-detail'),
    path('groups/<uuid:pk>/preview/', GroupPreviewView.as_view(), name='group-preview'),
    path('groups/<uuid:pk>/reconciliation/', GroupReconciliationView.as_view(), name='group-reconciliation'),
    path('groups/<uuid:pk>/picking-order/', AssignPickingOrderView.as_view(), name='group-picking-order'),
    path('groups/<uuid:pk>/play/', PlayNjangiView.as_view(), name='group-play'),
    path('groups/<uuid:pk>/social-fund/', SocialFundListCreateView.as_view(), name='group-social-fund'),
    path(
        'groups/<uuid:pk>/social-fund/<uuid:fund_id>/contribute/',
        ContributeSocialFundView.as_view(),
        name='group-social-fund-contribute',
    ),
    path('groups/<uuid:pk>/messages/', GroupMessageListCreateView.as_view(), name='group-messages'),
    path('groups/<uuid:pk>/savings/start/', StartSavingsPeriodView.as_view(), name='group-savings-start'),
    path('groups/<uuid:pk>/savings/', GroupSavingsView.as_view(), name='group-savings'),
    path('groups/<uuid:pk>/savings/deposit/', SavingsDepositView.as_view(), name='group-savings-deposit'),
    path('groups/<uuid:pk>/savings/withdraw/', SavingsWithdrawView.as_view(), name='group-savings-withdraw'),
    path('groups/<uuid:pk>/savings/close/', CloseSavingsPeriodView.as_view(), name='group-savings-close'),
    path(
        'groups/<uuid:pk>/membership-requests/',
        MembershipRequestListView.as_view(),
        name='group-membership-requests',
    ),
    path(
        'groups/<uuid:pk>/membership-requests/<uuid:req_id>/respond/',
        RespondMembershipRequestView.as_view(),
        name='group-membership-request-respond',
    ),
]
