# Generated by Django 5.2.15 on 2026-06-08 13:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NjangiGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('contribution_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('frequency', models.CharField(choices=[('Weekly', 'Weekly'), ('Bi-weekly', 'Bi-weekly'), ('Monthly', 'Monthly')], default='Monthly', max_length=20)),
                ('max_members', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('rules', models.TextField(blank=True)),
                ('invitation_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('fund_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cycle_progress', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('president', 'President'), ('treasurer', 'Treasurer'), ('member', 'Member')], default='member', max_length=20)),
                ('rotation_position', models.PositiveIntegerField(blank=True, null=True)),
                ('is_current_beneficiary', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='groups.njangigroup')),
            ],
            options={
                'ordering': ['rotation_position', 'joined_at'],
                'unique_together': {('group', 'user')},
            },
        ),
    ]
