# Generated by Django 5.2.15 on 2026-06-12 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0004_membershiprequest_savingsperiod_savingscontribution"),
    ]

    operations = [
        migrations.AddField(
            model_name="njangigroup",
            name="rotation_started",
            field=models.BooleanField(default=False),
        ),
    ]
