# Generated by Django 5.2.15 on 2026-06-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0005_njangigroup_rotation_started"),
    ]

    operations = [
        migrations.AddField(
            model_name="njangigroup",
            name="play_deadline_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="njangigroup",
            name="play_frequency",
            field=models.CharField(
                choices=[("weekly", "Weekly"), ("monthly", "Monthly")],
                default="monthly",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="njangigroup",
            name="play_week_of_month",
            field=models.CharField(
                blank=True,
                choices=[
                    ("first", "First"),
                    ("second", "Second"),
                    ("third", "Third"),
                    ("fourth", "Fourth"),
                    ("last", "Last"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="njangigroup",
            name="play_weekday",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
