# Generated by Django 5.2.15 on 2026-06-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0006_njangigroup_play_deadline_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="njangigroup",
            name="picking_mode",
            field=models.CharField(
                choices=[
                    ("random", "Random"),
                    ("manual", "Manual"),
                    ("mri_weighted", "Reliability (MRI) weighted"),
                ],
                default="random",
                max_length=20,
            ),
        ),
    ]
