# Generated by Django 5.2.15 on 2026-06-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0008_alter_groupmembership_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="njangigroup",
            name="late_payment_penalty",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
