# Generated by Django 5.2.15 on 2026-06-11 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="target_id",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="notification",
            name="target_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("group", "Group"),
                    ("loan", "Loan"),
                    ("transaction", "Transaction"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
