# Generated by Django 5.2.15 on 2026-06-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_notification_target_id_notification_target_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("payment_reminder", "Payment Reminder"),
                    ("loan_approval", "Loan Approval"),
                    ("contribution_confirmation", "Contribution Confirmation"),
                    ("upcoming_payout", "Upcoming Payout"),
                    ("group_announcement", "Group Announcement"),
                    ("mri_update", "MRI Update"),
                ],
                max_length=40,
            ),
        ),
    ]
