# Generated by Django 5.2.15 on 2026-06-14 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="target_view",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Default"),
                    ("members", "Members"),
                    ("ledger", "Ledger"),
                    ("savings", "Savings"),
                    ("loans", "Loans"),
                ],
                default="",
                help_text="Optional sub-view within the target (e.g. the Members tab of a group).",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("payment_reminder", "Payment Reminder"),
                    ("loan_approval", "Loan Approval"),
                    ("contribution_confirmation", "Contribution Confirmation"),
                    ("upcoming_payout", "Upcoming Payout"),
                    ("group_announcement", "Group Announcement"),
                    ("mri_update", "MRI Update"),
                    ("membership_request", "Membership Request"),
                ],
                max_length=40,
            ),
        ),
    ]
